### ISSUE TITLE
Server crash with Bibliocraft enchanted books copying

### ISSUE THREAD

**Issue by Quipex** [AustereTony-MCMods/Enchantments-Control#15]
Hello, whenever I try to create a copy of enchanted book on a [printing press](https://ftbwiki.org/Printing_Press), server crashes with the following:

java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
    at austeretony.enchcontrol.common.core.ECHooks.getTranslatedName(ECHooks.java:68)
    at net.minecraft.enchantment.Enchantment.func_77316_c(Enchantment.java:125)
    at jds.bibliocraft.tileentities.TileEntityPrintPress.plateName(TileEntityPrintPress.java:197)
    at jds.bibliocraft.tileentities.TileEntityPrintPress.smeltItem(TileEntityPrintPress.java:371)
    at jds.bibliocraft.tileentities.TileEntityPrintPress.func_73660_a(TileEntityPrintPress.java:279)
    at net.minecraft.world.World.func_72939_s(World.java:1835)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.resources.I18n
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 12 more

[click for a full crashlog on pastebin](https://pastebin.com/h2mDrkj7)

An enchantment is vanilla sharpness, although capped by this mod.

**Comment by AustereTony-MCMods** [comment]
Fixed in 1.1.5. If issue persists, please reopen this ticket.
