### ISSUE TITLE
Crash when hovering over an item with custom lore

### ISSUE THREAD

**Issue by Insane96** [AustereTony-MCMods/Enchantments-Control#16]
this is the item:
`minecraft:cobblestone, nbt:{ench:[{lvl:1,id:99}],display:{Lore:["§4DON'T PLACE ME!","§7Expose Me in an Item Frame"],Name:"§rCobblestone Trophy"}}`

This is the exception:
```
java.lang.NullPointerException: Rendering screen
	at austeretony.enchcontrol.common.enchantment.EnchantmentWrapper.get(EnchantmentWrapper.java:75)
	at austeretony.enchcontrol.common.core.ECHooks.modifyItemStackTooltip(ECHooks.java:235)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:712)
	at net.minecraft.client.gui.GuiScreen.func_191927_a(GuiScreen.java:143)
	at net.minecraft.client.gui.GuiScreen.func_146285_a(GuiScreen.java:137)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146285_a(GuiContainerCreative.java:737)
	at net.minecraft.client.gui.inventory.GuiContainer.func_191948_b(GuiContainer.java:175)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:684)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

Full crash log: https://pastebin.com/0qR73K44

**Comment by AustereTony-MCMods** [comment]
Fixed in 1.1.5. If issue persists, please reopen this ticket.
